HTTP:
  BASE_URL: "http://218.108.205.10"
  PORT: 80
LOG:
  #DEBUG INFO WARN ERROR
  CONSOLE_OUT: WARN
  FILE_OUT: INFO
#用户登录erp获取cookie

NGINX:
  INDEX_HTML: D:\tool\nginx179\html\index.html
  SERVER: "http://apk.zhonshian.com:201"

EMAIL:
  SMTP_SERVER: "stmp.qq.com"
  SENDER: "xx@qq.com"
  PASSWORD: xxxxxx
  RECEIVER:
    - "x1@qq.com"
    - "x2@163.com"
ERP_COOKIE:
  URL: "http://www.zhonshian.com"
  USER: test01
  PWD: '000000'

province_PC:
  user: "sjys"
  passwd: "111111"
  path: "/pro-api/zsabasedata/systemUser/login/pc"
  test_path:
    partyChef: "/pro-api/zsaledger/html/pc/partyChef/selectPcAll"
    partyFamily: "/pro-api/zsaledger/html/pc/partyFamily/selectPcAll"
    deleteFamily: "/pro-api/zsaledger/html/jgd/partyFamily/delete"
    deleteChef: "/pro-api/zsaledger/html/jgd/partyChef/delete"
    query_chef: "supId=3677307&education=&page=1&pageSize=10&healthCertificate=&keyword=删除厨师测试&startTime=&endTime="
    query_family: "supId=3677307&page=1&pageSize=10&buildInfo=&keyword=删除家宴中心测试&startCreateTime=&endCreateTime="


